Frontend/ShopSln/ShopWebApplication/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShopWebApplication.Helpers;
using ShopWebApplication.Models.POCOS;
using ShopWebApplication.Token;

namespace ShopWebApplication.Controllers
{
    public class BillController : Controller
    {
        #region Members
        private readonly HttpClient _client = new HttpClient();
        
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHttpContextAccessor _context;
        private static CommandModel _currentCommand;
        #endregion

        #region Constructor
        public BillController(IHttpContextAccessor context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        #endregion

        #region Action

        [Authorize(Roles = "Customer")]
        public IActionResult PreviewCommand()
        {
            var currentUserCommandHelper = CreateCommmad();
            if (currentUserCommandHelper.Ok)
                ViewBag.Success = currentUserCommandHelper.Message;
            else
                ViewBag.Error = currentUserCommandHelper.Message;
            return View("Preview", currentUserCommandHelper);
        }
        
        [Authorize(Roles = "Customer")]
        public IActionResult Preview()
        {
            var currentUserCommandHelper = GetCurrentCommand();
            if (currentUserCommandHelper.Ok)
                ViewBag.Success = currentUserCommandHelper.Message;
            else
                ViewBag.Error = currentUserCommandHelper.Message;
            return View("Preview", currentUserCommandHelper);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> Payment()
        {
            // var requetePost = Request.Form;
            //TODO : PAYEMENT LIRE HTTT REQUUEST
            
            var methode = Request.Form["methode"].First();
            var user = GetUser();
            var currentUserCommandHelper = ConfirmPayment(user, methode);
            
            if (currentUserCommandHelper.Ok)
                ViewBag.Success = currentUserCommandHelper.Message;
            else
                ViewBag.Error = currentUserCommandHelper.Message;
            return View("Preview", currentUserCommandHelper);
        }
        #endregion
        
        #region Method
        private UserModel GetUser()
        {
            var user = new UserModel();
            var currentUser = GetUserIdentity();
            try
            {
                using (var request = new HttpRequestMessage(HttpMethod.Get, $"http://{TokenManager.GetHost()}:{TokenManager.GetPort()}/cart/get/{currentUser.Name.ToLower()}"))
                {
                    _client.DefaultRequestHeaders.Accept.Clear();
                    request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", TokenManager.GetToken());

                    var reponse = _client.SendAsync(request).Result;
                    if (reponse.IsSuccessStatusCode)
                    {
                        var jsonString = reponse.Content.ReadAsStringAsync().Result;
                        user = JsonSerializer.Deserialize<UserModel>(jsonString);
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine($"{e.Source}: {e.Message}");
                return new UserModel();
            }
            return user;
        }
        private CurrentUser GetUserIdentity()
        {
            var currentUser = new CurrentUser();
            var user = _userManager.GetUserAsync(_context.HttpContext.User).Result;
            if (user != null)
            {
                currentUser.Name = user.UserName;
                if (_userManager.IsInRoleAsync(user, "Customer").Result)
                {
                    currentUser.Role = "Customer";
                }
                else if (_userManager.IsInRoleAsync(user, "Visitor").Result)
                {
                    currentUser.Role = "Visitor";
                }
            }
            return currentUser;
        }
        
        private CurrentUserCommandHelper CreateCommmad()
        {
            
            UserModel currentUser = GetUser();
            var totalElement = GetCurrentCommand().CurrentCommand.TotalElement;

            if (totalElement == 0)
            {
                using (var request = new HttpRequestMessage(HttpMethod.Get,
                    $"http://{TokenManager.GetHost()}:{TokenManager.GetPort()}/command/preview/{currentUser.Name}"))
                {
                    _client.DefaultRequestHeaders.Accept.Clear();
                    request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", TokenManager.GetToken());

                    var reponse = _client.SendAsync(request).Result;
                    if (reponse.IsSuccessStatusCode)
                    {
                        var jsonString = reponse.Content.ReadAsStringAsync().Result;
                        var commandCree = JsonSerializer.Deserialize<CommandModel>(jsonString);
                        return new CurrentUserCommandHelper(true, "Commande créee, en attente de validation",
                            currentUser, commandCree);
                    }
                }
                return new CurrentUserCommandHelper(false, "Erreur lors de la creation de la commande", currentUser, new CommandModel());
            }
            return new CurrentUserCommandHelper(false, "Une commande est en cours de validation, impossible de créer cette nouvelle commande", currentUser, new CommandModel());
        }

        private CurrentUserCommandHelper GetCurrentCommand()
        {
            var user = GetUser();
            //var currentUser = GetUserIdentity();
            var currentCommand = new CommandModel();
            try
            {
                using (var request = new HttpRequestMessage(HttpMethod.Get, $"http://{TokenManager.GetHost()}:{TokenManager.GetPort()}/command/current/{user.Name.ToLower()}"))
                {
                    _client.DefaultRequestHeaders.Accept.Clear();
                    request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", TokenManager.GetToken());

                    var reponse = _client.SendAsync(request).Result;
                    if (reponse.IsSuccessStatusCode)
                    {
                        var jsonString = reponse.Content.ReadAsStringAsync().Result;
                        currentCommand = JsonSerializer.Deserialize<CommandModel>(jsonString);
                        return new CurrentUserCommandHelper(true, "Cette commande est en attente de validation",user, currentCommand);
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine($"{e.Source}: {e.Message}");
                return new CurrentUserCommandHelper(user, new CommandModel());
            }
            return new CurrentUserCommandHelper(false, "Aucune commande en cours de validation",user, new CommandModel());
        }

        
        private CurrentUserCommandHelper ConfirmPayment(UserModel connectedUserModel, String deliveryMode)
        {
            var currentCommand = GetCurrentCommand();
            if (connectedUserModel.Wallet >= connectedUserModel.MyCartModel.TotalTva)
            {
                // using (var client = new HttpClient())
                
                using (var request = new HttpRequestMessage(HttpMethod.Get,
                    $"http://{TokenManager.GetHost()}:{TokenManager.GetPort()}/command/checkout/{currentCommand.CurrentCommand.Id}?methode={deliveryMode.ToLower()}"))
                {
                    _client.DefaultRequestHeaders.Accept.Clear();
                    request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", TokenManager.GetToken());
                    var reponse = _client.SendAsync(request).Result;
                    if (reponse.IsSuccessStatusCode)
                    {
                        //ViewBag.Success = "Payement effectué !";
                        var jsonString = reponse.Content.ReadAsStringAsync().Result;
                        var responseMesssage = JsonSerializer.Deserialize<ReponseMessage>(jsonString);
                        return new CurrentUserCommandHelper(true, responseMesssage.Message, connectedUserModel, GetCurrentCommand().CurrentCommand);
                    }
                    return new CurrentUserCommandHelper(false, "Erreur serveur lors de l'execution du paiement", connectedUserModel, currentCommand.CurrentCommand);

                    //ViewBag.Error = "Erreur serveur lors de l'execution du paiement! !";
                    //return new ReponseHelper(false, "Erreur serveur lors de l'execution du paiement!");
                }
            }
            return new CurrentUserCommandHelper(false, "Pas assez d'argent de le portefeuille", connectedUserModel, currentCommand.CurrentCommand);

            //return new ReponseHelper(false, "Pas assez d'argent de le portefeuille!");
        }
        #endregion
    }
}

Frontend/ShopSln/ShopWebApplication/Controllers/CommandController.cs
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShopWebApplication.Helpers;
using ShopWebApplication.Token;

namespace ShopWebApplication.Controllers
{
    public class CommandController : Controller
    {
        // GET
        #region Members
        private readonly HttpClient _client = new HttpClient();
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHttpContextAccessor _context;
        #endregion

        #region Constructor
        public CommandController(IHttpContextAccessor context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        #endregion

        #region Action
        [HttpGet]
        [Authorize(Roles = "Customer")]
        public IActionResult Commands()
        {
            return View("Commands", GetCommands());
        }
        #endregion

        #region Method
        private CurrentUser GetUserIdentity()
        {
            var currentUser = new CurrentUser();
            var user = _userManager.GetUserAsync(_context.HttpContext.User).Result;
            if (user != null)
            {
                currentUser.Name = user.UserName;
                if (_userManager.IsInRoleAsync(user, "Customer").Result)
                {
                    currentUser.Role = "Customer";
                }
                else if (_userManager.IsInRoleAsync(user, "Visitor").Result)
                {
                    currentUser.Role = "Visitor";
                }
            }
            return currentUser;
        }
        private UserCommandHelper GetCommands(){
        
            UserCommandHelper userCommandHelper = new UserCommandHelper(){Username = GetUserIdentity().Name};
            try
            {
                using (var request = new HttpRequestMessage(HttpMethod.Get,
                    $"http://{TokenManager.GetHost()}:{TokenManager.GetPort()}/command/list/{userCommandHelper.Username.ToLower()}"))
                {
                    _client.DefaultRequestHeaders.Accept.Clear();
                    request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", TokenManager.GetToken());

                    var reponse = _client.SendAsync(request).Result;
                    if (reponse.IsSuccessStatusCode)
                    {
                        var jsonString = reponse.Content.ReadAsStringAsync().Result;
                        userCommandHelper = JsonSerializer.Deserialize<UserCommandHelper>(jsonString);
                    }
                }
            }
            catch(Exception e)
            {
                return new UserCommandHelper();
            }
            return userCommandHelper;
        }
        #endregion
    }
}

Frontend/ShopSln/ShopWebApplication/Views/Shared/_CartCatalog.cshtml
@model ShopWebApplication.Models.POCOS.CartModel;
<div class="row mb-5 text-right">
    <div class="col-12">
        <a class="my-catalog-cart-container" asp-controller="Cart" asp-action="MyCart">
            <div class="my-catalog-cart">
                <svg width="74" height="74" viewBox="0 0 74 74" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M4.93332 4.93335C4.60645 4.92873 4.28193 4.98912 3.97861 5.111C3.67529 5.23289 3.39922 5.41385 3.16644 5.64336C2.93366 5.87287 2.74882 6.14635 2.62265 6.44792C2.49649 6.74949 2.43152 7.07312 2.43152 7.40002C2.43152 7.72691 2.49649 8.05055 2.62265 8.35212C2.74882 8.65369 2.93366 8.92717 3.16644 9.15668C3.39922 9.38619 3.67529 9.56715 3.97861 9.68903C4.28193 9.81092 4.60645 9.87131 4.93332 9.86669H9.56795C10.1252 9.86669 10.5901 10.2156 10.7483 10.7531L21.2605 46.4909C22.1831 49.6278 25.0845 51.8 28.357 51.8H55.4325C58.7586 51.8 61.6954 49.5521 62.5724 46.3464L68.9799 22.8504C69.0799 22.4844 69.0942 22.1002 69.0215 21.7278C68.9488 21.3554 68.7912 21.0048 68.561 20.7032C68.3307 20.4016 68.034 20.1572 67.6939 19.989C67.3538 19.8208 66.9794 19.7333 66.6 19.7334H18.5337L15.4841 9.36083C15.4825 9.36082 15.4809 9.36082 15.4793 9.36083C14.7099 6.74594 12.2914 4.93335 9.56795 4.93335H4.93332ZM29.6 56.7334C28.2916 56.7334 27.0368 57.2531 26.1116 58.1783C25.1864 59.1035 24.6666 60.3583 24.6666 61.6667C24.6666 62.9751 25.1864 64.2299 26.1116 65.1551C27.0368 66.0803 28.2916 66.6 29.6 66.6C30.9084 66.6 32.1632 66.0803 33.0884 65.1551C34.0136 64.2299 34.5333 62.9751 34.5333 61.6667C34.5333 60.3583 34.0136 59.1035 33.0884 58.1783C32.1632 57.2531 30.9084 56.7334 29.6 56.7334ZM54.2666 56.7334C52.9582 56.7334 51.7034 57.2531 50.7783 58.1783C49.8531 59.1035 49.3333 60.3583 49.3333 61.6667C49.3333 62.9751 49.8531 64.2299 50.7783 65.1551C51.7034 66.0803 52.9582 66.6 54.2666 66.6C55.5751 66.6 56.8299 66.0803 57.755 65.1551C58.6802 64.2299 59.2 62.9751 59.2 61.6667C59.2 60.3583 58.6802 59.1035 57.755 58.1783C56.8299 57.2531 55.5751 56.7334 54.2666 56.7334Z" fill="#000" />
                </svg>
                <div class="my-catalog-cart-bg">
                    <p><span id="current-cart-item">@(Model.TotalElement)</span></p>
                </div>
            </div>
        </a>
    </div>
    <div class="col-12">
        <p>Updated at @DateTime.Now</p>
    </div>
</div>

Frontend/ShopSln/ShopWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MyShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="icon" href="favicon.ico" />
</head>
<body>
<header>
    <nav class="my-nav navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyShop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="my-links navbar-nav flex-grow-1">
                    <li class="my-link nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="my-link nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="MyCatalog">Catalog</a>
                    </li>
                    <li class="my-link nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="MyCart">Cart</a>
                    </li>
                    <li class="my-link nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Login">Log in</a>
                    </li>
                    <li class="my-link nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Register">Register</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted catalog-footer ">
    <div class="container">
        &copy; 2020 - By Hendrick Samuel & Khamana B. Benedict
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

Frontend/ShopSln/ShopWebApplication/Views/Shared/_LayoutLogged.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="icon" href="favicon.ico" />

</head>
<body>
    <header>
        <nav class="my-nav navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="my-links navbar-nav flex-grow-1">
                        <li class="my-link nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="my-link nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="MyCatalog">Catalog</a>
                        </li>
                        <li class="my-link nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="MyCart">Cart</a>
                        </li>
                        <li class="my-link nav-item text-lg-right">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bill" asp-action="Preview">Commande en cours</a>
                        </li>
                        <li class="my-link nav-item text-lg-right">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Command" asp-action="Commands">Vos commandes</a>
                        </li>
                        <li class="my-link nav-item text-lg-right">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted catalog-footer ">
        <div class="container">
            &copy; 2020 - By Hendrick Samuel & Khamana B. Benedict
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>